steps:

  - id: 'Build App'
    name: 'node'
    script: |
      #! /usr/bin/env bash

      # Build the Svelte app
      cd svelte
      echo "Using Node version $(node --version)"
      npm install
      npm run build
      ls /workspace/svelte/build

  - id: 'Copy to Cloud Storage'
    name: 'google/cloud-sdk:slim'
    script: |
      #! /usr/bin/env bash
      gsutil -m rm -r gs://conversations.dora.dev/**
      gsutil cp -r /workspace/svelte/build/* gs://conversations.dora.dev/
      